
USE WineStore;

CREATE LOGIN ADMINISTRATOR_LOG
    WITH PASSWORD = 'admin',
	DEFAULT_DATABASE = [WineStore],
	DEFAULT_LANGUAGE = [english];

	
CREATE USER ADMINISTRATOR
    FOR LOGIN ADMINISTRATOR_LOG
	WITH DEFAULT_SCHEMA = [dbo];

GO
GRANT EXECUTE ON OBJECT::sp_AddWines TO ADMINISTRATOR;
GRANT EXECUTE ON OBJECT::sp_AlterWines TO ADMINISTRATOR;
GRANT EXECUTE ON OBJECT::sp_ExportWineToXML TO ADMINISTRATOR;
GRANT EXECUTE ON OBJECT::sp_ImportWineFromXML TO ADMINISTRATOR;
GO


go
CREATE LOGIN CLIENT_LOG
    WITH PASSWORD = '1111',
	DEFAULT_DATABASE = [WineStore],
	DEFAULT_LANGUAGE = [english];

go	
CREATE USER CLIENT
    FOR LOGIN CLIENT_LOG
	WITH DEFAULT_SCHEMA = [dbo];


GO
GRANT EXECUTE ON OBJECT::sp_UserVerification TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_UserLogOut TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_InsertUser TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectALLWines TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectAllWinesSortedPrice TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectAllWinesSortedName TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectAllWinesSortedVintage TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectWines TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_AddWinesToBasket TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectALLWinesToBasket TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_RemoveWineFromBasket TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_CreateOrder TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_InsertOrderInformation TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectALLOrders TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectShippingInformation TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_InsertToAboutUser TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_UpdateShippingInformation TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectPaymentInformation TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_InsertToCard TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_UpdatePaymentInformation TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectAllFaqs TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectFromFaqs TO CLIENT;
GRANT EXECUTE ON OBJECT::sp_SelectShopInfo TO CLIENT;
GO